# Generated by Django 4.1.6 on 2023-02-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя кота")),
                ("description", models.TextField(verbose_name="Описание")),
                ("breed", models.CharField(max_length=30, verbose_name="Порода")),
                ("age", models.IntegerField()),
            ],
        ),
    ]
