# Generated by Django 4.1.6 on 2023-02-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cats", options={"verbose_name": "Кот", "verbose_name_plural": "Коты"},
        ),
        migrations.AlterField(
            model_name="cats",
            name="age",
            field=models.IntegerField(verbose_name="Возраст"),
        ),
    ]
