# Generated by Django 4.1.6 on 2023-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainshop", "0003_alter_cats_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cats", name="age", field=models.IntegerField(default=0),
        ),
    ]
