# Generated by Django 4.1.6 on 2023-02-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainshop", "0004_alter_cats_age"),
    ]

    operations = [
        migrations.RemoveField(model_name="cats", name="age",),
    ]
