# Generated by Django 4.2 on 2023-05-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0006_cats_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='age',
            field=models.IntegerField(),
        ),
    ]
